// try{
//     let a=5;
//     console.log("Hello");
//     2=5;
// }
// catch(err){
//     console.log("error received");
// }

try {
    adddlert("Welcome guest!");
  }
  catch(err) {
    console.log(err);
  }